"""empty message

Revision ID: 049458a5349e
Revises: f5a198b003e0
Create Date: 2022-02-10 23:06:22.268216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '049458a5349e'
down_revision = 'f5a198b003e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'pokemon_team')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pokemon_team', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
