"""empty message

Revision ID: a4725ca4e376
Revises: 049458a5349e
Create Date: 2022-02-11 15:20:12.462083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4725ca4e376'
down_revision = '049458a5349e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'wins')
    op.drop_column('user', 'losses')
    op.drop_column('user', 'battles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('battles', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('losses', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('wins', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
