"""empty message

Revision ID: e47be5f0dd65
Revises: d397c2214442
Create Date: 2022-02-08 11:58:09.243777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e47be5f0dd65'
down_revision = 'd397c2214442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('abilities', sa.String(length=150), nullable=True))
    op.add_column('pokemon', sa.Column('hp', sa.String(length=150), nullable=True))
    op.add_column('pokemon', sa.Column('defense', sa.String(length=150), nullable=True))
    op.add_column('pokemon', sa.Column('attack', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pokemon', 'attack')
    op.drop_column('pokemon', 'defense')
    op.drop_column('pokemon', 'hp')
    op.drop_column('pokemon', 'abilities')
    # ### end Alembic commands ###
